<?php
namespace FlowerTest\View\Pane\IntegrationTest;

use Flower\View\Pane\PaneEvent;
use Flower\View\Pane\Service\ConfigFileListenerFactory;
use FlowerTest\Bootstrap;
use Zend\ServiceManager\ServiceManager;
use Zend\Mvc\Service\ServiceManagerConfig;
use Zend\View\Renderer\PhpRenderer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-06 at 23:02:41.
 */
class ManagerFactoryDomainIntegrationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigFileListenerFactory
     */
    protected $object;

    protected $serviceLocator;

    protected $paneCacheStorage;

    protected $renderCacheStorage;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $config = Bootstrap::getServiceManager()->get('ApplicationConfig');
        if (!isset($config['module_listener_options']['config_static_paths'])) {
            $config['module_listener_options']['config_static_paths'] = array();
        }
        $config['module_listener_options']['config_static_paths'][] = __DIR__ . '/TestAsset/manager_domain_integration.config.php';
        $serviceManager = new ServiceManager(new ServiceManagerConfig);
        $serviceManager->setService('ApplicationConfig', $config);
        $serviceManager->get('ModuleManager')->loadModules();
        $serviceManager->get('Application')->bootstrap();
        $this->serviceLocator = $serviceManager;
        //This is injected in post.route in MVC.
        $domainService = $this->serviceLocator->get('Flower_Domain_Service');
        $domainService->setCurrentDomainId(123);
        $this->helperManager = $this->serviceLocator->get('ViewHelperManager');
        $this->view = new PhpRenderer;
        $this->view->setHelperPluginManager($this->helperManager);
        $this->manager = $this->view->plugin('npPaneManager');
    }

    public function testCanGetPaneManager()
    {
        $this->assertInstanceOf('Flower\View\Pane\PaneManager', $this->manager);
    }

    public function testCanGetPaneInConfig()
    {
        $pane = $this->manager->get('bar');
        $this->assertInstanceOf('Flower\View\Pane\PaneClass\PaneInterface', $pane);
        $res = $this->manager->render('bar');
        $expected = '<!-- begin Renderer -->
<ul>
<li>
  <span class="container">Link Label 1</span>
<ul>
  <li>
    <span class="main">Link Label 1.1</span>
  <ul>
    <!-- start content CallbackRender -->
    <li>
    <span class="main">Link Label 1.1.1</span>
    </li>
    <!-- end content CallbackRender -->
  </ul>
  </li>
</ul>
</li>
</ul>
<!-- end Renderer -->
';
        $this->assertEquals(str_replace("\r\n", "\n", $expected), $res);
        //private teardown
        $this->manager->refresh('bar');
    }

    public function testCanGetPaneInFile()
    {
        $pane = $this->manager->get('foo');
        $this->assertInstanceOf('Flower\View\Pane\PaneClass\PaneInterface', $pane);
        $res = $this->manager->render('foo');
        $expected = '<!-- begin Renderer -->
<div id="foo">
</div>
<!-- end Renderer -->
';
        $this->assertEquals(str_replace("\r\n", "\n", $expected), $res);

        //private teardown
        $this->manager->refresh('foo');
    }

    public function testEventListnerIsAttached()
    {
        $eventManager = $this->manager->getEventManager();

        $listeners = $eventManager->getListeners(PaneEvent::EVENT_LOAD_CONFIG);
        $this->assertEquals(1, $listeners->count());

        $listeners = $eventManager->getListeners(PaneEvent::EVENT_GET_PANE);
        $this->assertEquals(2, $listeners->count());

        $listeners = $eventManager->getListeners(PaneEvent::EVENT_RENDER);
        $this->assertEquals(2, $listeners->count());
    }
}
