<?php

namespace FlowerTest\View\Pane\Utils;

use Flower\View\Pane\Utils\Gumby;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-17 at 11:53:31.
 */
class GumbyTest extends \PHPUnit_Framework_TestCase {


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Flower\View\Utils\Gumby::sizeToClass
     */
    public function testSizeToClass() {
        $this->assertEquals('three columns', Gumby::sizeToClass(3));
    }

}
