<?php
namespace Flower\AccessControl\RoleMapper;

use Flower\AccessControl\RoleMapper\RolePrefixRemoveFilter;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-22 at 23:59:27.
 */
class RolePrefixRemoveFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RolePrefixRemoveFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RolePrefixRemoveFilter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Flower\AccessControl\RoleMapper\RolePrefixRemoveFilter::filterWithPrefix
     * @todo   Implement testFilterWithPrefix().
     */
    public function testFilterWithPrefix()
    {
        $prefix = 'pre';
        $roles = array('pre.foo', 'pre.bar', 'baz', 'other.qux');
        $this->object->setPrefix($prefix);
        $this->assertEquals(array('foo', 'bar'), $this->object->filterWithPrefix($roles));
    }
}
