<?php
namespace FlowerTest\View\Pane\Service;

use Flower\View\Pane\Service\ConfigFileServiceFactory;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-09 at 18:24:51.
 */
class ConfigFileServiceFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigFileServiceFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigFileServiceFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testCreateService()
    {
        $config = array(
            'pane_config_file' => array(
                'spec_class' => 'Flower\File\Spec\TreeArrayMerge',
                'spec_options' => array(
                ),
                'resolve_spec_class' => 'Flower\File\Spec\Resolver\Tree',
                'resolve_spec_options' => array(
                    'map' => [],
                    'path_stack' => array(
                        'flower' => 'TestAsset/file',
                    ),
                ),
                'cache_spec_options' => array(
                    'cache_path' => 'TestAsset/tmp/cache',
                ),
            ),
        );
        $serviceLocator = new ServiceManager;
        $serviceLocator->setService('Config', $config);
        $res = $this->object->createService($serviceLocator);
        $this->assertInstanceOf('Flower\File\Gateway\GatewayInterface', $res);
    }
}
