<?php
namespace FlowerTest\View\Pane\Service;

use Flower\Test\TestTool;
use Flower\View\Pane\Service\ConfigFileListenerFactory;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-06 at 23:02:41.
 */
class ConfigFileListenerFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigFileListenerFactory
     */
    protected $object;

    protected $serviceLocator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigFileListenerFactory;
        $this->serviceLocator = new ServiceManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Flower\View\Pane\Service\ConfigFileListenerFactory::createService
     */
    public function testCreateServiceWithoutConfig()
    {
        $res = $this->object->createService($this->serviceLocator);
        $this->assertNull($res);
    }

    /**
     * @covers Flower\View\Pane\Service\ConfigFileListenerFactory::getFileService
     */
    public function testGetFileService()
    {
        $config = require 'TestAsset/file_service.config.php';
        $configKey = TestTool::getPropertyValue($this->object, 'configKey');
        $service = $this->object->getFileService($this->serviceLocator, $config[$configKey]);
        $this->assertInstanceOf('Flower\File\Gateway\GatewayInterface', $service);
    }

    /**
     * @covers Flower\View\Pane\Service\ConfigFileListenerFactory::createService
     */
    public function testCreateService()
    {
        $config = require 'TestAsset/file_service.config.php';
        $this->serviceLocator->setService('Config', $config);
        $service = $this->object->createService($this->serviceLocator);
        $this->assertInstanceOf('Flower\View\Pane\Service\ConfigFileListener', $service);
    }

}
