<?php
namespace FlowerTest\View\Pane\Entity;

use Flower\View\Pane\Entity\ApplicatableCallbackEntity;
use Flower\View\Pane\PaneClass\EntityAnchor;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-21 at 19:21:36.
 */
class ApplicatableCallbackEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Flower\View\Pane\Entity\ApplicatableCallbackEntity::apply
     */
    public function testApply()
    {
        $callback = function ($pane, array $params = array()) {
            echo get_class($pane);
        };
        $pane = new EntityAnchor;
        $params = array('foo' => 'bar');
        $object = new ApplicatableCallbackEntity($callback, $params);

        $this->expectOutputString(get_class($pane));
        $object->apply($pane);
    }

    /**
     * @covers Flower\View\Pane\Entity\ApplicatableCallbackEntity::apply
     */
    public function testApplyParams()
    {
        $callback = function ($pane, array $params = array()) {
            var_export($params);
        };
        $pane = new EntityAnchor;
        $params = array('foo' => 'bar');
        $object = new ApplicatableCallbackEntity($callback, $params);

        $this->expectOutputString(var_export($params, true));
        $object->apply($pane);
    }
}
