<?php
namespace FlowerTest\ServiceLayer;

use Flower\Test\TestTool;
use Flower\ServiceLayer\ServiceLayerPluginManager;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-15 at 19:18:03.
 */
class ServiceLayerPluginManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServiceLayerPluginManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ServiceLayerPluginManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Flower\ServiceLayer\ServiceLayerPluginManager::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $service = $this->getMock('Flower\ServiceLayer\ServiceLayerInterface');
        $this->object->setService('foo', $service);
        $wrapped = new \ArrayObject(array($service));
        $wrapper = $this->getMock('stdClass', array('wrap'));
        $wrapper->expects($this->once())
                ->method('wrap')
                ->with($service)
                ->will($this->returnValue($wrapped));
        $this->object->addServiceWrapper($wrapper);
        $res = $this->object->get('foo');
        $this->assertSame($wrapped, $res);
    }

    /**
     * @covers Flower\ServiceLayer\ServiceLayerPluginManager::validatePlugin
     */
    public function testValidatePlugin()
    {
        $mock = $this->getMock('Flower\ServiceLayer\ServiceLayerInterface');
        $this->object->validatePlugin($mock);
        //特にチェックする必要はない。
    }
    /**
     * @covers Flower\ServiceLayer\ServiceLayerPluginManager::validatePlugin
     * @expectedException Flower\ServiceLayer\Exception\RuntimeException
     */
    public function testValidatePluginInvalid()
    {
        $service = new \stdClass;
        $this->object->validatePlugin($service);
    }

    /**
     * @covers Flower\ServiceLayer\ServiceLayerPluginManager::addServiceWrapper
     * @todo   Implement testAddServiceWrapper().
     */
    public function testAddServiceWrapper()
    {
        $wrapper = new \stdClass;
        $this->object->addServiceWrapper($wrapper);
        $this->assertSame($wrapper, TestTool::getPropertyValue($this->object, 'wrappers')[0]);
    }
}
