<?php
namespace FlowerTest\Hash;

use Flower\Hash\Hash1;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-27 at 00:31:56.
 */
class Hash1Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Flower\Hash\Hash1::getSalt
     */
    public function testGetSalt()
    {
        $ref = new \ReflectionClass('Flower\Hash\Hash1');
        $prop = $ref->getProperty('salt');
        $prop->setAccessible(true);
        $prop->setValue(md5('123'));
        $this->assertEquals(md5('123'), Hash1::getSalt());
    }

    /**
     * @covers Flower\Hash\Hash1::hash
     */
    public function testHash()
    {
        $credential = 'test';
        $ref = new \ReflectionClass('Flower\Hash\Hash1');
        $prop = $ref->getProperty('salt');
        $prop->setAccessible(true);
        $prop->setValue(md5('123'));
        // dummy
        //How to test?
        $this->assertEquals(Hash1::hash($credential, 'prefix'), Hash1::hash($credential, 'prefix'));
    }
}
