<?php
namespace FlowerTest\View\Pane;

use Flower\Test\TestTool;
use FlowerTest\Bootstrap;
use Zend\Mvc\Router\Http\RouteMatch;
use Zend\Mvc\Service\ServiceManagerConfig;
use Zend\ServiceManager\ServiceManager;
use Zend\View\Renderer\PhpRenderer;

/**
 * rendering文字列中に下記が現れる場合
* RouteMatch does not contain a matched route name
*  RouteMatchにmatchedRouteNameが設定されていない場合
*
*
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-01 at 22:15:54.
 */
class AnchorAdvanceFunctionalTest extends \PHPUnit_Framework_TestCase
{
    protected $serviceLocator;

    protected $router;

    protected $helper;

    protected $view;

    public function setUp()
    {
        $config = Bootstrap::getServiceManager()->get('ApplicationConfig');
        $serviceManager = new ServiceManager(new ServiceManagerConfig());
        $serviceManager->setService('ApplicationConfig', $config);
        $serviceManager->get('ModuleManager')->loadModules();
        $serviceManager->get('Application')->bootstrap();
        $this->serviceLocator = $serviceManager;
        $this->router = $this->serviceLocator->get('HttpRouter');
        $params = array(
            'controller' => 'test',
            'action' => 'index',
            'foo' => 'bar',
        );
        $routeMatch = new RouteMatch($params);
        $routeMatch->setMatchedRouteName('application/default');
        $application = $this->serviceLocator->get('Application');
        $application->getMvcEvent()->setRouteMatch($routeMatch);
        $this->helperManager = $this->serviceLocator->get('ViewHelperManager');
        $this->view = new PhpRenderer;
        $this->view->setHelperPluginManager($this->helperManager);
        $this->helper = $this->view->plugin('npNavi');

    }

    public function testEnv()
    {
        $renderer = $this->helperManager->getRenderer();
        $this->assertInstanceOf('Zend\View\Renderer\PhpRenderer', $renderer);

        $this->assertInstanceOf('Flower\View\Pane\AnchorHelper', $this->helper);

        $builder = $this->helper->getBuilder();
        $this->assertEquals('Flower\View\Pane\Anchor', TestTool::getPropertyValue($builder, 'paneClass'));
    }

    public function testMultiInner()
    {
        $expected =
'<!-- begin ListRenderer -->
<ul>
  <li>
  <a href="/application/">
/application/
  </a>
  <ul>
    <!-- start content ListPane -->
    <li>
    <a href="/application/">
/application/
    </a>
    </li>
    <!-- end content ListPane -->
  </ul>
  </li>
</ul>
<!-- end ListRenderer -->
';
        $expected = str_replace("\r\n","\n", $expected);
        $paneConfig = array(
            'classes' => 'container',
            'var' => 'content',
            'inner' => array(
                'classes' => 'main',
                'var' => 'anchor',
                'inner' => array(
                    'classes' => 'main',
                    'var' => 'content',
                ),
            ),
        );
        $renderer = $renderer = $this->helper->__invoke($paneConfig);
        $renderer->setVar('content', 'foo');
        $renderer->setVar('anchor', '<a href="dummy">from view script</a>');
        $this->assertEquals($expected, str_replace("\r\n","\n", (string) $renderer));
    }

    public function testMultiInnerCommentOff()
    {
        $expected = '<ul><li><a href="/application/">/application/</a><ul><li><a href="/application/">/application/</a></li></ul></li></ul>';
        $paneConfig = array(
            'classes' => 'container',
            'var' => 'content',
            'inner' => array(
                'classes' => 'main',
                'var' => 'anchor',
                'inner' => array(
                    'classes' => 'main',
                    'var' => 'content',
                ),
            ),
        );
        $renderer = $this->helper->__invoke($paneConfig);
        $renderer->commentEnable = false;
        $renderer->indent = "";
        $renderer->linefeed = "";
        $renderer->setVar('content', 'foo');
        $renderer->setVar('anchor', '<a href="foo">bar</a>');
        $this->assertEquals($expected, (string) $renderer);
    }
}
